_prefs: 
  baselayer: ''
  mapid: ''
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href=\"http://vcgi.vermont.gov\" target=\"_blank\">VCGI</a>, <a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -72.7625
  - 43.9375
  - 8
description: A map for following the oldest long-distance hiking trail in America.
format: "png8:m=h:c=128"
interactivity_layer: ''
layers: 
  - landcover
  - landuse
  - hillshade
  - contour.line
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - contour.label
maxzoom: 22
minzoom: 0
name: The Long Trail
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5"
styles: 
  - vars.mss
  - bg.mss
  - labels.mss
  - roads.mss
  - pois.mss
template: ''
